# Generated by Django 4.2.14 on 2024-08-02 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.DecimalField(decimal_places=4, max_digits=20)),
                ('payment_no', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
            options={
                'db_table': 'paymets',
            },
        ),
    ]
