# Generated by Django 4.2.14 on 2024-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_paymets_payments_alter_payments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='notes',
            field=models.TextField(blank=True, db_column='description', default=''),
        ),
    ]
