# Generated by Django 4.2.14 on 2024-08-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
    ]
