# Generated by Django 4.2.14 on 2024-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Parent Name'),
        ),
    ]
