# Generated by Django 4.2.14 on 2024-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_parent_options_student_note_alter_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to='images/students'),
        ),
    ]
